name: 'Lambda Function AWS Signature Version 4 Action'
author: 'Nexthink'
branding:
  icon: 'check-square'  
  color: 'blue'
description: 'Facilitate AWS Signature Version 4 signing process to interact with AWS Lambda function URL using AWS_IAM Auth type.'
inputs: 
  lambda-url:
    description: 'The lambda function URL, should be https://<id>.lambda-url.<region>.on.aws/'
    required: true
  body:
    description: 'The body associated with the request (POST request)'
    required: false
  method:
    description: 'HTTP Method used to call the Lambda function'
    required: false
    default: GET
  # Headers list
  # with:
  #   headers: |
  #     Content-Type: "application/json"
  #     User-Agent: "GitHub-Hookshot/760256b"
  headers:
    description: 'A list of headers to add to the HTTP request'
    required: false
outputs:
  status:
    description: "Response HTTP Status"
  code:
    description: "Response HTTP Code"
  message:
    description: "Response body"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "-lambda-url=${{ inputs.lambda-url }}"
    - "-body=${{ inputs.body }}"
    - "-method=${{ inputs.method }}"
    - "-headers=${{ inputs.headers }}"
  